# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Release

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types:
      - "published"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Test
        run: dotnet test --configuration Release --verbosity normal
  
  release:
    if: github.event_name == 'release'
    needs: [ test ]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PACKAGE_KEY }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Pack
        run: dotnet pack src/LibUringSharp --configuration Release /p:Version=${VERSION} --output .
      - name: Push to github packages
        run: dotnet nuget push QRWells.LibUringSharp.${VERSION}.nupkg --source https://nuget.pkg.github.com/QRWells/index.json --api-key ${GITHUB_TOKEN}
      - name: Push to nuget
        run: dotnet nuget push QRWells.LibUringSharp.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}